title: Joy Of Life
baseURL: /
params:
  palette: blue
  header:
    title: Joy Of Life
    logo_img: /images/joy-of-life.png
    has_nav: true
    nav_links:
      - label: Accueil
        url: /
      - label: Voyages
        url: /blog3
      - label: Beauté
        url: /blog

  footer:
    subscribe_title: Subscribe
    subscribe_content: Stay up to date with our latest developments.
    has_subscribe: false
    social_title: Mes Réseaux
    social_links:
      - label: Instagram
        url: https://www.instagram.com/joyoflife2019/?hl=fr
        new_window: true
    tagline: Live the life of your dreams
    logo_img: /images/joy-of-life-2.png
    has_social: true
    content: "&copy; Netary. Tous droits réservés."
    nav_title: Mes Articles
    nav_links:
      - label: Voyages
        url: /blog3
      - label: Beauté
        url: /blog
    has_nav: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
